### ISSUE TITLE
Correct package versions which runs the predictor

### ISSUE THREAD

**Issue by mauliknshah** [zhejilab/PolyaModelsHuman#4]
With the given versions in the `README` file, you will find the issue #2 (`Metaclass` error), and #3 (`H5` file loading error) if you have been able to resolve the `metaclass` error. I was able to run the predictor with the following package versions, and it would really be helpful if you update your `README` with that: 

```
python=3.6
tensorflow=2.0.0
keras=2.3.1
h5py=2.10.0
numpy=1.19.1
pandas=1.1.5
pyfaidx=0.7.2.1
isolearn=0.2.1
```

Notes: 
- Versions of `numpy`, `pandas`, and `pyfaidx` are optimally selected by `mamba`.
- I installed `isolearn` with `pip` and the rest with `conda`.

**Comment by ekstroup** [comment]
Thank you for these helpful suggestions in setting up the working environment. I've added your notes to the readme.
